### ISSUE TITLE
.destroy(cb)

### ISSUE THREAD

**Issue by jaruba** [thibauts/node-upnp-mediarenderer-client#16] opened 2015-05-31 23:21 UTC
How about a method to efficiently destroy the ``node-upnp-mediarenderer-client`` instance?

**Comment by thibauts** [comment] 2015-06-01 19:51
What would it release and what would it exactly do ?

**Comment by jaruba** [comment] 2015-06-01 21:51
If I cast a video and the video ends, the normal solution would be to restart ``node-upnp-mediarenderer-client`` with a different video url.

To do that, I would also need to destroy the previous instance (which will no longer be needed), so I guess it should probably do ``client.stop();`` then disconnect, maybe remove listeners..

**Comment by thibauts** [comment] 2015-06-01 22:36
There shouldn't be any listeners hanging, or memory leak when you dereference the client, by design. You only have to remove the listeners you have registered and everything will go fine. Maybe a `close` method that calls `this.removeAllListeners` for all possibly registered events would make it. If you submit a PR in this respect I'll happily merge it.

**Comment by jaruba** [comment] 2015-06-01 23:51
how about ``client.server.close()``?

**Comment by thibauts** [comment] 2015-06-02 08:58
Why not a straight `client.close()` ?

**Comment by jaruba** [comment] 2015-06-04 00:21
I meant that ``client`` also creates a server (it's actually created by ``upnp-device-client``). So I guess that needs to be closed too.

Does this look correct to you?

	MediaRendererClient.prototype.close = function(callback) {
		this.stop();
		this.removeAllListeners();
		if (this.server) this.server.close(callback || noop);
		else if (typeof callback === 'function') callback();
	};

I also added ``this.stop()`` because the server can't be closed unless it stops being busy so without stopping the stream before running ``server.close()`` it will keep ``node-upnp-mediarenderer-client`` alive until the video ends and only then it will call the callback function.

Also, I know checking if ``this.server`` exists does not tell me if the server is actually running, but tbh I haven't found anything that can check if a server is active except listening for the ``listening`` event which doesn't help in this scenario..

Unfortunately I can't test this code until I get back to a Samsung TV which should be in a couple of days.

**Comment by thibauts** [comment] 2015-06-04 15:21
The server is released as soon as you have unsubscribed from all events you had registered to. See [this code](https://github.com/thibauts/node-upnp-device-client/blob/master/index.js#L317)

**Closed** 2016-06-02 23:05 UTC
